mgr/dashboard: SSO error: AttributeError: 'str' object has no attribute 'decode'
The token is `str` in PyJWT >= 2 and Python3. Check `controllers/auth.py` where the same code is used.

Resolves: rhbz#2216920

Fixes: https://tracker.ceph.com/issues/59689
References: https://github.com/SUSE/ceph/pull/506

Signed-off-by: Volker Theile <vtheile@suse.com>
(cherry picked from commit 0fc6e7637657a96acfb0aa01dde6b3fbd81a136d)
(cherry picked from commit 73c45735ba6aed9777eaeabd30c84adb96d20189)